### ISSUE TITLE
[memory-leak] incorrect false

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#2373]
$ esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --add-symex-value-sets --no-align-check --k-step 2 --floatbv --unlimited-k-steps --no-vla-size-check array-realloc-2.c --32 --witness-output witness.graphml --memory-leak-check --no-reachable-memory-leak --no-assertions --no-abnormal-memory-leak --malloc-zero-is-null --incremental-bmc

````C
#include <stdlib.h>

extern int __VERIFIER_nondet_int(void);

int num, ind, newsize, i = 1;

void *expandArray(int **pointer) {
  while (newsize < num) {
    newsize = newsize + 1;
    int *temp = realloc(*pointer, sizeof(int) * newsize);
    if (temp != NULL) {
      temp[newsize - 1] = i;
      *pointer = temp;
    } else {
      return 0;
    }
  }

  return 0;
}

int main(int argc, char **argv) {
  num = __VERIFIER_nondet_int();
  if (!(num > 0 && num < 100)) {
    return 0;
  }
  int *a = (int *)malloc(sizeof(int));
  if (a == NULL) {
    return 0;
  }
  newsize = 0;
  expandArray(&a);
  free(a);
  return 0;
}
````

````
format_version: '2.0'

# old file name: array-realloc_true-valid-memsafety.i
input_files: 'array-realloc-2.i'

properties:
  - property_file: ../properties/no-overflow.prp
    expected_verdict: true
  - property_file: ../properties/valid-memsafety.prp
    expected_verdict: true
  - property_file: ../properties/coverage-branches.prp
  - property_file: ../properties/coverage-conditions.prp
  - property_file: ../properties/coverage-statements.prp

options:
  language: C
  data_model: ILP32
````

````
[Counterexample]


State 3 file array-realloc-2.c line 23 column 9 function main thread 0
----------------------------------------------------
  num = 1 (00000000 00000000 00000000 00000001)

State 7 file array-realloc-2.c line 10 column 5 function expandArray thread 0
----------------------------------------------------
  temp = (signed int *)0

State 11 file array-realloc-2.c line 35 column 1 function main thread 0
----------------------------------------------------
Violated property:
  file array-realloc-2.c line 35 column 1 function main
  dereference failure: forgotten memory: dynamic_3_array


VERIFICATION FAILED

Bug found (k = 1)
````
